name: Publish JS to GitHub Pages

description: Build and publish a JavaScript application to Pages

branding:
  icon: upload-cloud
  color: blue

inputs:
  node_version:
    description: Version of NodeJS to install
    default: "18"

  install_command:
    description: Shell command to install dependencies
    default: npm ci

  build_command:
    description: Shell command to build the application
    default: npm run build
  
  build_output_directory:
    description: Directory into which built files are placed
    default: build

outputs:
  page_url:
    description: URL of the Pages site after deploying
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
    
    - run: |
        ${{ inputs.install_command }}
        ${{ inputs.build_command }}
      shell: bash
    
    - uses: actions/configure-pages@v4
    
    - uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ inputs.build_output_directory }}
    
    - id: deployment
      uses: actions/deploy-pages@v4
